server:
  port: 1001
  servlet:
    context-path: aop-redis-limit
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 50
      max: 1000
  # Redis
  redis:
    host: 192.168.206.128
    port: 6379
    password: lilishop
    lettuce:
      pool:
        # ???????????????????? ?? 8
        max-active: 200
        # ??????????????????????? ?? -1
        max-wait: 20
        # ??????????? ?? 8
        max-idle: 10
        # ??????????? ?? 8
        min-idle: 8

lili:
  cache:
    timeout: 1500
