server:
  port: 1101
  servlet:
    context-path: /aop-redis-limit
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 50
      max: 1000
  # Redis
  redis:
    host: k12code.online
    port: 6379
    password: lilishop
    lettuce:
      pool:
        # ???????????????????? ?? 8
        max-active: 200
        # ??????????????????????? ?? -1
        max-wait: 20
        # ??????????? ?? 8
        max-idle: 10
        # ??????????? ?? 8
        min-idle: 8
spring:
  task:
    execution:
      pool:
        max-threads: 10
        core-threads: 5
lili:
  cache:
    timeout: 1500
