spring:
  application:
    name: rocketmq-consumer
  redis:
    host: 123.249.70.145
    port: 6379
    password: 333333
    lettuce:
      pool:
        # ???????????????????? ?? 8
        max-active: 200
        # ??????????????????????? ?? -1
        max-wait: 20
        # ??????????? ?? 8
        max-idle: 10
        # ??????????? ?? 8
        min-idle: 8
server:
  port: 1201
rocketmq:
  name-server: 123.249.70.145:9876

